# Generated by Terraform user_data — do not edit on the instance; change prod.tfvars and re-apply.

# --- Flask API ---
FLASK_APP=${flask_app}
FLASK_ENV=${flask_env}
FLASK_DEBUG=${flask_debug}
SECRET_KEY=${secret_key}
JWT_SECRET_KEY=${jwt_secret_key}
JWT_ACCESS_TOKEN_EXPIRES_MINUTES=${jwt_access_token_expires_minutes}
JWT_REFRESH_TOKEN_EXPIRES_DAYS=${jwt_refresh_token_expires_days}
RESET_TOKEN_EXP_MINUTES=${reset_token_exp_minutes}
DEFAULT_USER_ROLE=${default_user_role}

DATABASE_URL=${database_url}
REDIS_URL=${redis_url}
CELERY_BROKER_URL=${celery_broker_url}
CELERY_RESULT_BACKEND=${celery_result_backend}

DEFAULT_TENANT_SUBDOMAIN=${default_tenant_subdomain}
BACKEND_URL=${backend_url}
FRONTEND_URL=${frontend_url}
CORS_ORIGINS=${cors_origins}
SESSION_COOKIE_SECURE=${session_cookie_secure}
SESSION_COOKIE_SAMESITE=${session_cookie_samesite}

SMTP_SERVER=${smtp_server}
SMTP_PORT=${smtp_port}
EMAIL_ADDRESS=${email_address}
EMAIL_PASSWORD=${email_password}
DEFAULT_SENDER_NAME=${default_sender_name}
MAIL_USE_TLS=${mail_use_tls}
MAIL_USE_SSL=${mail_use_ssl}

AWS_REGION=${aws_region}
AWS_S3_BUCKET_NAME=${aws_s3_bucket_name}
S3_BUCKET_NAME=${s3_bucket_name}
S3_ENV_PREFIX=${s3_env_prefix}

PORT=${port}
GUNICORN_BIND=${gunicorn_bind}
WEB_CONCURRENCY=${web_concurrency}
GUNICORN_WORKERS=${gunicorn_workers}
GUNICORN_THREADS=${gunicorn_threads}
GUNICORN_TIMEOUT=${gunicorn_timeout}

# --- Next.js (admin-web + panel; same file via env_file) ---
NODE_ENV=${node_env}
NEXT_TELEMETRY_DISABLED=${next_telemetry_disabled}
NODE_OPTIONS=${node_options}
NEXT_PUBLIC_API_URL=${next_public_api_url}
NEXT_PUBLIC_API_URL_DEV=${next_public_api_url}
NEXT_PUBLIC_GATEWAY_ORIGIN=${next_public_gateway_origin}
